// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"strings"

	"github.com/kataras/iris/v12"
	"github.com/oapi-codegen/oapi-codegen/v2/pkg/openapi"
	"github.com/oapi-codegen/runtime"
	strictiris "github.com/oapi-codegen/runtime/strictmiddleware/iris"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /json)
	JSONExample(ctx iris.Context)

	// (POST /multipart)
	MultipartExample(ctx iris.Context)

	// (POST /multipart-related)
	MultipartRelatedExample(ctx iris.Context)

	// (POST /multiple)
	MultipleRequestAndResponseTypes(ctx iris.Context)

	// (GET /reserved-go-keyword-parameters/{type})
	ReservedGoKeywordParameters(ctx iris.Context, pType string)

	// (POST /reusable-responses)
	ReusableResponses(ctx iris.Context)

	// (POST /text)
	TextExample(ctx iris.Context)

	// (POST /unknown)
	UnknownExample(ctx iris.Context)

	// (POST /unspecified-content-type)
	UnspecifiedContentType(ctx iris.Context)

	// (POST /urlencoded)
	URLEncodedExample(ctx iris.Context)

	// (POST /with-headers)
	HeadersExample(ctx iris.Context, params HeadersExampleParams)

	// (POST /with-union)
	UnionExample(ctx iris.Context)
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc iris.Handler

// JSONExample converts iris context to params.
func (w *ServerInterfaceWrapper) JSONExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.JSONExample(ctx)
}

// MultipartExample converts iris context to params.
func (w *ServerInterfaceWrapper) MultipartExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.MultipartExample(ctx)
}

// MultipartRelatedExample converts iris context to params.
func (w *ServerInterfaceWrapper) MultipartRelatedExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.MultipartRelatedExample(ctx)
}

// MultipleRequestAndResponseTypes converts iris context to params.
func (w *ServerInterfaceWrapper) MultipleRequestAndResponseTypes(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.MultipleRequestAndResponseTypes(ctx)
}

// ReservedGoKeywordParameters converts iris context to params.
func (w *ServerInterfaceWrapper) ReservedGoKeywordParameters(ctx iris.Context) {

	var err error

	// ------------- Path parameter "type" -------------
	var pType string

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Params().Get("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		ctx.StatusCode(http.StatusBadRequest)
		ctx.Writef("Invalid format for parameter type: %s", err)
		return
	}

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.ReservedGoKeywordParameters(ctx, pType)
}

// ReusableResponses converts iris context to params.
func (w *ServerInterfaceWrapper) ReusableResponses(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.ReusableResponses(ctx)
}

// TextExample converts iris context to params.
func (w *ServerInterfaceWrapper) TextExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.TextExample(ctx)
}

// UnknownExample converts iris context to params.
func (w *ServerInterfaceWrapper) UnknownExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.UnknownExample(ctx)
}

// UnspecifiedContentType converts iris context to params.
func (w *ServerInterfaceWrapper) UnspecifiedContentType(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.UnspecifiedContentType(ctx)
}

// URLEncodedExample converts iris context to params.
func (w *ServerInterfaceWrapper) URLEncodedExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.URLEncodedExample(ctx)
}

// HeadersExample converts iris context to params.
func (w *ServerInterfaceWrapper) HeadersExample(ctx iris.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HeadersExampleParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "header1" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("header1")]; found {
		var Header1 string
		n := len(valueList)
		if n != 1 {
			ctx.StatusCode(http.StatusBadRequest)
			ctx.Writef("Expected one value for header1, got %d", n)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "header1", valueList[0], &Header1, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			ctx.StatusCode(http.StatusBadRequest)
			ctx.Writef("Invalid format for parameter header1: %s", err)
			return
		}

		params.Header1 = Header1
	} else {
		ctx.StatusCode(http.StatusBadRequest)
		ctx.WriteString("Header header1 is required, but not found")
		return
	}
	// ------------- Optional header parameter "header2" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("header2")]; found {
		var Header2 int
		n := len(valueList)
		if n != 1 {
			ctx.StatusCode(http.StatusBadRequest)
			ctx.Writef("Expected one value for header2, got %d", n)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "header2", valueList[0], &Header2, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			ctx.StatusCode(http.StatusBadRequest)
			ctx.Writef("Invalid format for parameter header2: %s", err)
			return
		}

		params.Header2 = &Header2
	}

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.HeadersExample(ctx, params)
}

// UnionExample converts iris context to params.
func (w *ServerInterfaceWrapper) UnionExample(ctx iris.Context) {

	// Invoke the callback with all the unmarshaled arguments
	w.Handler.UnionExample(ctx)
}

// IrisServerOption is the option for iris server
type IrisServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *iris.Application, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, IrisServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *iris.Application, si ServerInterface, options IrisServerOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.Post(options.BaseURL+"/json", wrapper.JSONExample)
	router.Post(options.BaseURL+"/multipart", wrapper.MultipartExample)
	router.Post(options.BaseURL+"/multipart-related", wrapper.MultipartRelatedExample)
	router.Post(options.BaseURL+"/multiple", wrapper.MultipleRequestAndResponseTypes)
	router.Get(options.BaseURL+"/reserved-go-keyword-parameters/:type", wrapper.ReservedGoKeywordParameters)
	router.Post(options.BaseURL+"/reusable-responses", wrapper.ReusableResponses)
	router.Post(options.BaseURL+"/text", wrapper.TextExample)
	router.Post(options.BaseURL+"/unknown", wrapper.UnknownExample)
	router.Post(options.BaseURL+"/unspecified-content-type", wrapper.UnspecifiedContentType)
	router.Post(options.BaseURL+"/urlencoded", wrapper.URLEncodedExample)
	router.Post(options.BaseURL+"/with-headers", wrapper.HeadersExample)
	router.Post(options.BaseURL+"/with-union", wrapper.UnionExample)

	router.Build()
}

type JSONExampleRequestObject struct {
	Body *JSONExampleJSONRequestBody
}

type JSONExampleResponseObject interface {
	VisitJSONExampleResponse(ctx iris.Context) error
}

type JSONExample200JSONResponse = Example

func (response JSONExample200JSONResponse) VisitJSONExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "application/json")
	ctx.StatusCode(200)

	return ctx.JSON(&response)
}

type JSONExample400Response struct {
}

func (response JSONExample400Response) VisitJSONExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type MultipartExampleRequestObject struct {
	Body *multipart.Reader
}

type MultipartExampleResponseObject interface {
	VisitMultipartExampleResponse(ctx iris.Context) error
}

type MultipartExample200MultipartResponse func(writer *multipart.Writer) error

func (response MultipartExample200MultipartResponse) VisitMultipartExampleResponse(ctx iris.Context) error {
	writer := multipart.NewWriter(ctx.ResponseWriter())
	ctx.ResponseWriter().Header().Set("Content-Type", writer.FormDataContentType())
	ctx.StatusCode(200)

	defer writer.Close()
	return response(writer)
}

type MultipartExample400Response struct {
}

func (response MultipartExample400Response) VisitMultipartExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type MultipartRelatedExampleRequestObject struct {
	Body *multipart.Reader
}

type MultipartRelatedExampleResponseObject interface {
	VisitMultipartRelatedExampleResponse(ctx iris.Context) error
}

type MultipartRelatedExample200MultipartResponse func(writer *multipart.Writer) error

func (response MultipartRelatedExample200MultipartResponse) VisitMultipartRelatedExampleResponse(ctx iris.Context) error {
	writer := multipart.NewWriter(ctx.ResponseWriter())
	ctx.ResponseWriter().Header().Set("Content-Type", mime.FormatMediaType("multipart/related", map[string]string{"boundary": writer.Boundary()}))
	ctx.StatusCode(200)

	defer writer.Close()
	return response(writer)
}

type MultipartRelatedExample400Response struct {
}

func (response MultipartRelatedExample400Response) VisitMultipartRelatedExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type MultipleRequestAndResponseTypesRequestObject struct {
	JSONBody      *MultipleRequestAndResponseTypesJSONRequestBody
	FormdataBody  *MultipleRequestAndResponseTypesFormdataRequestBody
	Body          io.Reader
	MultipartBody *multipart.Reader
	TextBody      *MultipleRequestAndResponseTypesTextRequestBody
}

type MultipleRequestAndResponseTypesResponseObject interface {
	VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error
}

type MultipleRequestAndResponseTypes200JSONResponse = Example

func (response MultipleRequestAndResponseTypes200JSONResponse) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "application/json")
	ctx.StatusCode(200)

	return ctx.JSON(&response)
}

type MultipleRequestAndResponseTypes200FormdataResponse = Example

func (response MultipleRequestAndResponseTypes200FormdataResponse) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "application/x-www-form-urlencoded")
	ctx.StatusCode(200)

	if form, err := runtime.MarshalForm(response, nil); err != nil {
		return err
	} else {
		_, err := ctx.WriteString(form.Encode())
		return err
	}
}

type MultipleRequestAndResponseTypes200ImagepngResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response MultipleRequestAndResponseTypes200ImagepngResponse) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		ctx.ResponseWriter().Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.StatusCode(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.ResponseWriter(), response.Body)
	return err
}

type MultipleRequestAndResponseTypes200MultipartResponse func(writer *multipart.Writer) error

func (response MultipleRequestAndResponseTypes200MultipartResponse) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	writer := multipart.NewWriter(ctx.ResponseWriter())
	ctx.ResponseWriter().Header().Set("Content-Type", writer.FormDataContentType())
	ctx.StatusCode(200)

	defer writer.Close()
	return response(writer)
}

type MultipleRequestAndResponseTypes200TextResponse string

func (response MultipleRequestAndResponseTypes200TextResponse) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "text/plain")
	ctx.StatusCode(200)

	_, err := ctx.WriteString(string(response))
	return err
}

type MultipleRequestAndResponseTypes400Response struct {
}

func (response MultipleRequestAndResponseTypes400Response) VisitMultipleRequestAndResponseTypesResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type ReservedGoKeywordParametersRequestObject struct {
	Type string `json:"type"`
}

type ReservedGoKeywordParametersResponseObject interface {
	VisitReservedGoKeywordParametersResponse(ctx iris.Context) error
}

type ReservedGoKeywordParameters200TextResponse string

func (response ReservedGoKeywordParameters200TextResponse) VisitReservedGoKeywordParametersResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "text/plain")
	ctx.StatusCode(200)

	_, err := ctx.WriteString(string(response))
	return err
}

type ReusableResponsesRequestObject struct {
	Body *ReusableResponsesJSONRequestBody
}

type ReusableResponsesResponseObject interface {
	VisitReusableResponsesResponse(ctx iris.Context) error
}

type ReusableResponses200ResponseHeaders struct {
	Header1 string
	Header2 int
}

type ReusableResponses200JSONResponse struct {
	Body    Example
	Headers ReusableResponses200ResponseHeaders
}

func (response ReusableResponses200JSONResponse) VisitReusableResponsesResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	ctx.ResponseWriter().Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	ctx.ResponseWriter().Header().Set("Content-Type", "application/json")
	ctx.StatusCode(200)

	return ctx.JSON(&response.Body)
}

type ReusableResponses400Response struct {
}

func (response ReusableResponses400Response) VisitReusableResponsesResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type TextExampleRequestObject struct {
	Body *TextExampleTextRequestBody
}

type TextExampleResponseObject interface {
	VisitTextExampleResponse(ctx iris.Context) error
}

type TextExample200TextResponse string

func (response TextExample200TextResponse) VisitTextExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "text/plain")
	ctx.StatusCode(200)

	_, err := ctx.WriteString(string(response))
	return err
}

type TextExample400Response struct {
}

func (response TextExample400Response) VisitTextExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type UnknownExampleRequestObject struct {
	Body io.Reader
}

type UnknownExampleResponseObject interface {
	VisitUnknownExampleResponse(ctx iris.Context) error
}

type UnknownExample200Videomp4Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response UnknownExample200Videomp4Response) VisitUnknownExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "video/mp4")
	if response.ContentLength != 0 {
		ctx.ResponseWriter().Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.StatusCode(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.ResponseWriter(), response.Body)
	return err
}

type UnknownExample400Response struct {
}

func (response UnknownExample400Response) VisitUnknownExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type UnspecifiedContentTypeRequestObject struct {
	ContentType string
	Body        io.Reader
}

type UnspecifiedContentTypeResponseObject interface {
	VisitUnspecifiedContentTypeResponse(ctx iris.Context) error
}

type UnspecifiedContentType200VideoResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response UnspecifiedContentType200VideoResponse) VisitUnspecifiedContentTypeResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		ctx.ResponseWriter().Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.StatusCode(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.ResponseWriter(), response.Body)
	return err
}

type UnspecifiedContentType400Response struct {
}

func (response UnspecifiedContentType400Response) VisitUnspecifiedContentTypeResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type UnspecifiedContentType401Response struct {
}

func (response UnspecifiedContentType401Response) VisitUnspecifiedContentTypeResponse(ctx iris.Context) error {
	ctx.StatusCode(401)
	return nil
}

type UnspecifiedContentType403Response struct {
}

func (response UnspecifiedContentType403Response) VisitUnspecifiedContentTypeResponse(ctx iris.Context) error {
	ctx.StatusCode(403)
	return nil
}

type URLEncodedExampleRequestObject struct {
	Body *URLEncodedExampleFormdataRequestBody
}

type URLEncodedExampleResponseObject interface {
	VisitURLEncodedExampleResponse(ctx iris.Context) error
}

type URLEncodedExample200FormdataResponse = Example

func (response URLEncodedExample200FormdataResponse) VisitURLEncodedExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("Content-Type", "application/x-www-form-urlencoded")
	ctx.StatusCode(200)

	if form, err := runtime.MarshalForm(response, nil); err != nil {
		return err
	} else {
		_, err := ctx.WriteString(form.Encode())
		return err
	}
}

type URLEncodedExample400Response struct {
}

func (response URLEncodedExample400Response) VisitURLEncodedExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type HeadersExampleRequestObject struct {
	Params HeadersExampleParams
	Body   *HeadersExampleJSONRequestBody
}

type HeadersExampleResponseObject interface {
	VisitHeadersExampleResponse(ctx iris.Context) error
}

type HeadersExample200ResponseHeaders struct {
	Header1 string
	Header2 int
}

type HeadersExample200JSONResponse struct {
	Body    Example
	Headers HeadersExample200ResponseHeaders
}

func (response HeadersExample200JSONResponse) VisitHeadersExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	ctx.ResponseWriter().Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	ctx.ResponseWriter().Header().Set("Content-Type", "application/json")
	ctx.StatusCode(200)

	return ctx.JSON(&response.Body)
}

type HeadersExample400Response struct {
}

func (response HeadersExample400Response) VisitHeadersExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

type UnionExampleRequestObject struct {
	Body *UnionExampleJSONRequestBody
}

type UnionExampleResponseObject interface {
	VisitUnionExampleResponse(ctx iris.Context) error
}

type UnionExample200ResponseHeaders struct {
	Header1 string
	Header2 int
}

type UnionExample200ApplicationAlternativePlusJSONResponse struct {
	Body    Example
	Headers UnionExample200ResponseHeaders
}

func (response UnionExample200ApplicationAlternativePlusJSONResponse) VisitUnionExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	ctx.ResponseWriter().Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	ctx.ResponseWriter().Header().Set("Content-Type", "application/alternative+json")
	ctx.StatusCode(200)

	return ctx.JSON(&response.Body)
}

type UnionExample200JSONResponse struct {
	Body struct {
		union json.RawMessage
	}
	Headers UnionExample200ResponseHeaders
}

func (response UnionExample200JSONResponse) VisitUnionExampleResponse(ctx iris.Context) error {
	ctx.ResponseWriter().Header().Set("header1", fmt.Sprint(response.Headers.Header1))
	ctx.ResponseWriter().Header().Set("header2", fmt.Sprint(response.Headers.Header2))
	ctx.ResponseWriter().Header().Set("Content-Type", "application/json")
	ctx.StatusCode(200)

	return ctx.JSON(&response.Body.union)
}

type UnionExample400Response struct {
}

func (response UnionExample400Response) VisitUnionExampleResponse(ctx iris.Context) error {
	ctx.StatusCode(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /json)
	JSONExample(ctx context.Context, request JSONExampleRequestObject) (JSONExampleResponseObject, error)

	// (POST /multipart)
	MultipartExample(ctx context.Context, request MultipartExampleRequestObject) (MultipartExampleResponseObject, error)

	// (POST /multipart-related)
	MultipartRelatedExample(ctx context.Context, request MultipartRelatedExampleRequestObject) (MultipartRelatedExampleResponseObject, error)

	// (POST /multiple)
	MultipleRequestAndResponseTypes(ctx context.Context, request MultipleRequestAndResponseTypesRequestObject) (MultipleRequestAndResponseTypesResponseObject, error)

	// (GET /reserved-go-keyword-parameters/{type})
	ReservedGoKeywordParameters(ctx context.Context, request ReservedGoKeywordParametersRequestObject) (ReservedGoKeywordParametersResponseObject, error)

	// (POST /reusable-responses)
	ReusableResponses(ctx context.Context, request ReusableResponsesRequestObject) (ReusableResponsesResponseObject, error)

	// (POST /text)
	TextExample(ctx context.Context, request TextExampleRequestObject) (TextExampleResponseObject, error)

	// (POST /unknown)
	UnknownExample(ctx context.Context, request UnknownExampleRequestObject) (UnknownExampleResponseObject, error)

	// (POST /unspecified-content-type)
	UnspecifiedContentType(ctx context.Context, request UnspecifiedContentTypeRequestObject) (UnspecifiedContentTypeResponseObject, error)

	// (POST /urlencoded)
	URLEncodedExample(ctx context.Context, request URLEncodedExampleRequestObject) (URLEncodedExampleResponseObject, error)

	// (POST /with-headers)
	HeadersExample(ctx context.Context, request HeadersExampleRequestObject) (HeadersExampleResponseObject, error)

	// (POST /with-union)
	UnionExample(ctx context.Context, request UnionExampleRequestObject) (UnionExampleResponseObject, error)
}

type StrictHandlerFunc = strictiris.StrictIrisHandlerFunc
type StrictMiddlewareFunc = strictiris.StrictIrisMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// JSONExample operation middleware
func (sh *strictHandler) JSONExample(ctx iris.Context) {
	var request JSONExampleRequestObject

	var body JSONExampleJSONRequestBody
	if err := ctx.ReadJSON(&body); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.JSONExample(ctx, request.(JSONExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JSONExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(JSONExampleResponseObject); ok {
		if err := validResponse.VisitJSONExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// MultipartExample operation middleware
func (sh *strictHandler) MultipartExample(ctx iris.Context) {
	var request MultipartExampleRequestObject

	if reader, err := ctx.Request().MultipartReader(); err == nil {
		request.Body = reader
	} else {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MultipartExample(ctx, request.(MultipartExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MultipartExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(MultipartExampleResponseObject); ok {
		if err := validResponse.VisitMultipartExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// MultipartRelatedExample operation middleware
func (sh *strictHandler) MultipartRelatedExample(ctx iris.Context) {
	var request MultipartRelatedExampleRequestObject

	if _, params, err := mime.ParseMediaType(ctx.Request().Header.Get("Content-Type")); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if boundary := params["boundary"]; boundary == "" {
		ctx.StopWithError(http.StatusBadRequest, http.ErrMissingBoundary)
		return
	} else {
		request.Body = multipart.NewReader(ctx.Request().Body, boundary)
	}

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MultipartRelatedExample(ctx, request.(MultipartRelatedExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MultipartRelatedExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(MultipartRelatedExampleResponseObject); ok {
		if err := validResponse.VisitMultipartRelatedExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// MultipleRequestAndResponseTypes operation middleware
func (sh *strictHandler) MultipleRequestAndResponseTypes(ctx iris.Context) {
	var request MultipleRequestAndResponseTypesRequestObject

	if strings.HasPrefix(ctx.GetHeader("Content-Type"), "application/json") {

		var body MultipleRequestAndResponseTypesJSONRequestBody
		if err := ctx.ReadJSON(&body); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
		request.JSONBody = &body
	}
	if strings.HasPrefix(ctx.GetHeader("Content-Type"), "application/x-www-form-urlencoded") {
		if err := ctx.Request().ParseForm(); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
		var body MultipleRequestAndResponseTypesFormdataRequestBody
		if err := runtime.BindForm(&body, ctx.Request().Form, nil, nil); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
		request.FormdataBody = &body
	}
	if strings.HasPrefix(ctx.GetHeader("Content-Type"), "image/png") {
		request.Body = ctx.Request().Body
	}
	if strings.HasPrefix(ctx.GetHeader("Content-Type"), "multipart/form-data") {
		if reader, err := ctx.Request().MultipartReader(); err == nil {
			request.MultipartBody = reader
		} else {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	}
	if strings.HasPrefix(ctx.GetHeader("Content-Type"), "text/plain") {
		data, err := io.ReadAll(ctx.Request().Body)
		if err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
		body := MultipleRequestAndResponseTypesTextRequestBody(data)
		request.TextBody = &body
	}

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MultipleRequestAndResponseTypes(ctx, request.(MultipleRequestAndResponseTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MultipleRequestAndResponseTypes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(MultipleRequestAndResponseTypesResponseObject); ok {
		if err := validResponse.VisitMultipleRequestAndResponseTypesResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// ReservedGoKeywordParameters operation middleware
func (sh *strictHandler) ReservedGoKeywordParameters(ctx iris.Context, pType string) {
	var request ReservedGoKeywordParametersRequestObject

	request.Type = pType

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReservedGoKeywordParameters(ctx, request.(ReservedGoKeywordParametersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReservedGoKeywordParameters")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(ReservedGoKeywordParametersResponseObject); ok {
		if err := validResponse.VisitReservedGoKeywordParametersResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// ReusableResponses operation middleware
func (sh *strictHandler) ReusableResponses(ctx iris.Context) {
	var request ReusableResponsesRequestObject

	var body ReusableResponsesJSONRequestBody
	if err := ctx.ReadJSON(&body); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReusableResponses(ctx, request.(ReusableResponsesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReusableResponses")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(ReusableResponsesResponseObject); ok {
		if err := validResponse.VisitReusableResponsesResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// TextExample operation middleware
func (sh *strictHandler) TextExample(ctx iris.Context) {
	var request TextExampleRequestObject

	data, err := io.ReadAll(ctx.Request().Body)
	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	body := TextExampleTextRequestBody(data)
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TextExample(ctx, request.(TextExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TextExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(TextExampleResponseObject); ok {
		if err := validResponse.VisitTextExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// UnknownExample operation middleware
func (sh *strictHandler) UnknownExample(ctx iris.Context) {
	var request UnknownExampleRequestObject

	request.Body = ctx.Request().Body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnknownExample(ctx, request.(UnknownExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnknownExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(UnknownExampleResponseObject); ok {
		if err := validResponse.VisitUnknownExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// UnspecifiedContentType operation middleware
func (sh *strictHandler) UnspecifiedContentType(ctx iris.Context) {
	var request UnspecifiedContentTypeRequestObject

	request.ContentType = ctx.GetContentTypeRequested()

	request.Body = ctx.Request().Body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnspecifiedContentType(ctx, request.(UnspecifiedContentTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnspecifiedContentType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(UnspecifiedContentTypeResponseObject); ok {
		if err := validResponse.VisitUnspecifiedContentTypeResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// URLEncodedExample operation middleware
func (sh *strictHandler) URLEncodedExample(ctx iris.Context) {
	var request URLEncodedExampleRequestObject

	if err := ctx.Request().ParseForm(); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	var body URLEncodedExampleFormdataRequestBody
	if err := runtime.BindForm(&body, ctx.Request().Form, nil, nil); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.URLEncodedExample(ctx, request.(URLEncodedExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "URLEncodedExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(URLEncodedExampleResponseObject); ok {
		if err := validResponse.VisitURLEncodedExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// HeadersExample operation middleware
func (sh *strictHandler) HeadersExample(ctx iris.Context, params HeadersExampleParams) {
	var request HeadersExampleRequestObject

	request.Params = params

	var body HeadersExampleJSONRequestBody
	if err := ctx.ReadJSON(&body); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HeadersExample(ctx, request.(HeadersExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadersExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(HeadersExampleResponseObject); ok {
		if err := validResponse.VisitHeadersExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// UnionExample operation middleware
func (sh *strictHandler) UnionExample(ctx iris.Context) {
	var request UnionExampleRequestObject

	var body UnionExampleJSONRequestBody
	if err := ctx.ReadJSON(&body); err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	}
	request.Body = &body

	handler := func(ctx iris.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnionExample(ctx, request.(UnionExampleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnionExample")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.StopWithError(http.StatusBadRequest, err)
		return
	} else if validResponse, ok := response.(UnionExampleResponseObject); ok {
		if err := validResponse.VisitUnionExampleResponse(ctx); err != nil {
			ctx.StopWithError(http.StatusBadRequest, err)
			return
		}
	} else if response != nil {
		ctx.Writef("Unexpected response type: %T", response)
		return
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTXPbNhD9Kxi0p5QUZccn3hpPJm3T1h3ZPnV8WBFLCQkJoMBStEaj/94BQX1ZtCol",
	"+uhkcpPIxdvle7uLBWY806XRChU5ns64RWe0ctj8GYKw+E+Fjvw/gS6z0pDUiqf8HYhB+24ecYuVg2GB",
	"i+XePtOKUDVLwZhCZuCXJp+cXz/jLhtjCf7XjxZznvIfklUoSXjrEnyG0hTI5/N59CKCu4884mMEgbaJ",
	"Nvy82sSmqUGeckdWqhH3IMHsutNMKsIRWu/Nm7ZBeINFHOmMG6sNWpKBowkUFXZ7ap/o4SfMKHyBVLne",
	"5vJWKwKpHBMyz9GiItaSxzyGY64yRltCwYZT5j1kxBzaCVoecZLkA+P3689ZG7DjEZ+gdcHRVa/f63u9",
	"tEEFRvKUv20eRdwAjZsPWgpkdJfuv93f/cmkY1CRLoFkBkUxZSVYN4YCBZOKtA+xysj1eOPJNsL/KtrV",
	"71sqfdY0CfROi+kpEqbJy7V0vu73z5SX84jfBGddGMugkrUCa2ByqIoOzh/VZ6VrxdBabdsvS8qqIGnA",
	"0rpWm2z/sTDZh/IlXpJrW8YCCE7E+rE8XZr42GIBhGIPAQbB8jAd1uBPqsLX+LmoBm0/7uxT92NdOzbW",
	"NSPNBELBakljtlj4osFKxYA5qUYFskVQUaeYBbbb3s9KDNpvefAYJ+9n0QbKc1zXddwUUGULVJkWXyZh",
	"xGUJI0yMGm0u99hAPOXDKfmU3d7gjlTIESd8psQUINXu3ftMLf0700cr7FCuFpupRMQjHX/Gaa2tiA1Y",
	"KJHQumTmvc898Ag7SvmvpSXLQLEhMgUlCgY5oWUfNGsh3VbJDlq/H/THYLKCakae5Z/07xn3lDRjEI+4",
	"d8DTwEqoa2m96GQrjHbQ9vSf+flVAizYDMN2vOGquw0uWtSSOou58y2xS7kO/oKnwZrFZYa23Rm3dfw4",
	"xx7klXx963/A573GriO2vnPX9qGEVeHh65y1q/ah7Qs76R4sTqRAnZTm5kDki5HqDGYylyji9iviENtr",
	"LeFWq8wibY5A/kinNLElmD9p0hhZYCBiTrMaWVk5YgacY5KaLlLIcFoVuNU8HleR3QZPD6t2ukvVNyfS",
	"9M2lFL3pXx2+5O2J82ZjlHmlHge/vw82h57ZjzYzHTjxHc/vhcrZH1LitUut7hL+JRis9vQM5cRPREow",
	"i1RZhYJNJCwuYrZqswVYydo1C4UwVtPQ4oLtkIEo2ol1vYGVQ+G6wFa3ck/f8J3RKe8yz5W4lZK77g4f",
	"/WvWDtUvNwup1f/0ZhAKQquA5AR/Os6RchtFK7zLm9J7oXK0p4enby+r5hEPl9mhJ1W28I2DyKRJEi7B",
	"e66G0QhtT+oEjPQs/BsAAP//cdIkn9EYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi.T, err error) {
	resolvePath := PathToRawSpec("")
	_ = resolvePath // TODO: Use resolvePath when ReadFromURIFunc is implemented

	loader := openapi.NewLoader()
	loader.IsExternalRefsAllowed = true
	// TODO: Add ReadFromURIFunc support to our abstraction layer
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	// Use LoadFromDataWithBasePath with current directory as base path
	swagger, err = loader.LoadFromDataWithBasePath(specData, ".")
	if err != nil {
		return
	}
	return
}
